import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import NavBar from '../components/NavBar'
import Project from '../components/Project'
import Skill from '../components/Skill'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Abdillah | Ally</title>
        <meta name="description" content="Generated by create next app" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
      <About />
      <Skill />  
      <Project />
      {/* <Project /> */}
      <Contact /> 
      
    </div>
  )
}
