import Head from "next/head";
// import Image from 'next/image'
// import Link from 'next/link'
import About from "../components/About";
import Contact from "../components/Contact";
import Main from "../components/Main";
import Education from "../components/Education";

import Navbar from "../components/Navbar";
import Project from "../components/Project";
import Skill from "../components/Skill";
import Tabs from "../components/Tabs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Abdillah Ally</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Education />
      <Skill />
      <Project />
      <Contact />
    </div>
  );
}
